### ISSUE TITLE
UX improvement suggestion: show context menu on tab

### ISSUE THREAD

**Issue by igorlogius** [coolsoft-ita/autopintab#11]
It is a bit "unexpected" that the autopintab menu doesnt show up, when a tab is right clicked, so 
adding the `'tab'` value to the `contexts` property of `browser.menus.create` call would maybe be good idea. 

```
    browser.contextMenus.create({
        ...
        contexts: ["all"],  // << add "tab" here :) 
        ... 
```

refs.
-  https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/ContextType
-  https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create

**Comment by nicorac** [comment]
That's a great suggestion, thanks for it.
I've committed it here: 711e24023f3ee3a7218069b8989e788842e64c1a

You'll find it in next 1.3.0 version 😉

**Comment by nicorac** [comment]
Version 1.3.0 approved and available on FF Addons website:
https://addons.mozilla.org/firefox/addon/autopintab/
