### ISSUE TITLE
RegEx: Are negative lookaheads possible?

### ISSUE THREAD

**Issue by knobhead** [coolsoft-ita/autopintab#3]
Hi,

thanks for your helpful little add-on. I especially enjoy the possiblity to use Regular Expressions in die URL list.

I was just wondering if it is possible to use **negative lookaheads** in the matching URLs list?
Like so:
`https:\/\/mydomain\.tld\/(cloud|rss|mail|wallabag)\/(?!.*(prefs|subscribe|admin))`

**Use case:** Some web-apps should be auto-pinned as I need them constantly. If they open specific sub-URLs in new Tabs, I don't want these to be pinned (e.g. admin Pages or setting dialogues), as I don't need them anymore after I finished the administrative task.

I've prepared an example here: https://regexr.com/45t2s

regards

**Comment by nicorac** [comment]
> I was just wondering if it is possible to use negative lookaheads in the matching URLs list?

Yes it's possible, isn't it working on your side?
In the sample you've posted you used **PCRE** RegEx style, but remember that you must use **Javascript** one. Anyway, even switching to Javascript mode, your RegEx works without issues on regexr.com...

So the RegEx should be entered like this in AutoPinTab (no need to escape forward slashes):
`^https://mydomain\.tld/(cloud|rss|mail|wallabag)/(?!.*(prefs|subscribe|admin))`

PS: the source code that matches URLs against patterns is this:
https://github.com/coolsoft-ita/autopintab/blob/fcf648a763ba2b666104771edea0eae1141eb0d9/background/background.js#L111
As you can see the pattern is passed as parameter to RegEx object, so there's no need to "wrap" it into "/" and escape them.

**Comment by nicorac** [comment]
Feel free to reopen this issue if you have anu update ;)
