### ISSUE TITLE
Feature suggestion: also using "document.referrer" to determine whether pin tab or not

### ISSUE THREAD

**Issue by DRSAgile** [coolsoft-ita/autopintab#4]
Hi,

This extension is certainly useful, thanks to @nicorac for that.

But it can be even better if it would be also able to a regex check a new tab's _document.referrer_ to determine whether to pin it or not.

For example, if I open a YouTube video from another YouTube video or from a random different place, I do not want it to be pinned. But if I open it from my YouTube's Subscriptions tab, then it has to be pinned. In the latter case _document.referrer_ is "https://www.youtube.com/feed/subscriptions?flow=2".

In general, _document.referrer_ has either of the following types of values:
1. "" (empty string) if a user just clicked on the browser's "+" button to open a new tab and entered a site URL s/he wants to visit. Nothing to check here.
2. "[current URL]", meaning it is equal to _window.location_, if a user has opened the tab from outside of the browser (for example, from an electronic mail notification) or from a pop-up notification within the browser (usually appears in the bottom right corner of the viewport area). Again, nothing of interest this time.
3. "[actual referrer URL string]" -- the only useful case in to check it against a regex to see if the tab should be pinned or not. The limitation (for security reasons) is that if a tab is opened from a different domain, the browser would only show domain there, not a full URL. It will be enough to be useful in most cases, though*.

________________________
>###### * A way to almost curcumvent the limitation would be to upkeep an array of opened tabs (the chore is unavoidable because browsers are evil about this so they do not allow programmers to see _openerTabId_ property of any tabs other than opened by their own program with the use of _tabs.create_ method) and check/compare new tab's URL versus previously active tab's URL in the context of _document.referrer_. Of course, this is a narrower use case which is of a lesser necessity, so it can be implemented later.

**Comment by nicorac** [comment]
Need to check what's returned by `document.referrer` property, but I wonder if a new regex test is really necessary or a boolean flag could be enough?

I mean something like "Do not pin child of already pinned tabs within the same domain...".

**Comment by DRSAgile** [comment]
In my example, if a new tab (after passing the first regex pattern check) with YouTube video has _document.referrer_ equal to "https://www.youtube.com/feed/subscriptions?flow=2", then it means that this new tab with a YouTube video should be pinned as it was opened exactly from YouTube Subscriptions page.

But if this new tab was opened not from Subscriptions but, say, from a tab with a YouTube video, then such new tab should not be pinned.

So there have to be two conditions: first, that the tab itself is a YouTube video, not anything else; second, that it was opened from Subscriptions, and not from anything else.

Thus it looks like it would require two _regex_ patterns, right?

**Comment by nicorac** [comment]
Sorry to say that this feature cannot be implemented :(

AutoPinTab attaches to `browser.tabs.onCreated` event, generated by Firefox each time a new tab is created (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/onCreated).
The event returns an instance of a `tabs.Tab` object describing the new tab (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab), but this object does not contain any reference to `referrer`.

A workaround to get this info could be injecting a content script into page, but the injected content script is very limited in which informations it could retrieve about the page it was injected into; `referrer` is not one of them :(

Finally, we need to wait for the page to be loaded before accessing the `document` object, with the bad effect that the decision pin/notPin will be delayed after the page hsa been fully loaded... unacceptable.

**Comment by DRSAgile** [comment]
For my case, I used a Monkey Userscript to implement the feature by adding `[?|&]feature=pin-this-tab` to links on the source tab and then adding the same thing to your extension's regex option; it is a good workaround. 

As for a general solution within the extension, yes, you are right, the interface does not provide access to _document.referrer_ right through the _Tab_ object, but if the object is available it in the extension, then it also has _Tab.openerTabId_ property, from where _Tab.url_ for the opener tab can be taken and checked if it matches another _regex_.

By the way, the situation with the _document.referrer_ property is not that bad either because, at least in my tests, it is immediately accessible even with `@run-at document-start` condition when nothing else of essence is available other than empty _documentElement_, so it is not necessary to wait for anything in this sense; the property is filled properly:

`
// ==UserScript==

// @name YouTube Test

// @namespace Violentmonkey Scripts

// @include https://www.youtube.com/*

// @run-at document-start

console.log('YouTube Test: document.referrer', document.referrer);
`
