### ISSUE TITLE
Feature suggest: Position

### ISSUE THREAD

**Issue by alexander-williamson** [coolsoft-ita/autopintab#6]
Is there any way to set which tab position the pin appears at (for example 1, 2, 3) etc?

**Comment by nicorac** [comment]
Actually not, but a WebExtension can move/reorder tabs with `browser.tabs.move()` method.

I wonder why you suggested an _absolute position_ (1, 2, 3, ...) instead of a _relative_ one (always first, always last, ...).

Think about this situation: no pinned tab yet and AutoPinTab is going to autopin a tab with **2** as its pinned position? It will go on position 1 (first)...
Now, what should happen if you automatically (or manually) pin another tab? Should this new one go to position **1** (to obey the pos **2** setting of the previous one)?
If yes, this will overcomplicate each pin, because each already-pinned tab must be reevaluated to position it in the required slot...

I think a simpler option like "always pin at first position" could be more intuitive, do you agree?

**Comment by alexander-williamson** [comment]
My usage would be that I want certain tabs pinned on a certain order.
For example I want my work chat tab as the first tab, my WhatsApp as the second tab, Spotify as the third, and the rest as unpinned tabs.
```Chat (pinned) | WhatsApp (pinned) | Spotify (pinned) | (rest of unpinned tabs)```

I'd expect the standard behaviour if you pin another non-matching tab (e.g., to the right / end of the other pinned tabs).

If you open another tab that matches your patterns, I expect it to open to the right of the other pins in that family. For example if I opened another WhatsApp tab, it would be pinned next to the other matching WhatsApp tabs.
```Chat (pinned) | WhatsApp (pinned) | WhatsApp (2) (pinned) | Spotify (pinned) | (rest of unpinned tabs)```

**Comment by nicorac** [comment]
I've just started a new [pin-order](https://github.com/coolsoft-ita/autopintab/tree/pin-order) branch for this feature.

It's actually implemented like this:
- the patterns list (in options page) is now sortable by dragging rows up and down with mouse
- once you've set your desired pattern order, new tabs will be pinned respecting this same order (the topmost pattern --> the leftmost pinned tab)

To test it:
- download the [latest pin-order branch version](https://github.com/coolsoft-ita/autopintab/archive/pin-order.zip)
- follow the instructions in README file to load it in your Firefox

Please check it out, I'm waiting for your thoughts (and suggestions)...

**Comment by grahamwhiteuk** [comment]
I'm migrating from Chrome to Firefox.  On Chrome, I've been using the [Pin Tab](https://chrome.google.com/webstore/detail/pin-tab/dgldedkigbbalaioohedddpameekglma) extension.  The ability to automatically pin tabs is an absolutely must have for me so I was super pleased to find this extension - thanks for creating it.

I was going to open a similar feature request to this one.  The Chrome extension I was using allows you to specify a tab index so you can order the pinned tabs that are automatically opened.

Are you still developing this extension and indeed the [pin-order](https://github.com/coolsoft-ita/autopintab/tree/pin-order) branch?  If so, I'm happy to support with testing or anything else you need.   Thanks again.

**Comment by nicorac** [comment]
Of course I am, and I'm personally using the `pin-order` branch.
I haven't released it yet because (I suppose) I'm the only one who ever tested it 😄.

Feel free to test it and report your thoughts...

**Comment by grahamwhiteuk** [comment]
OK, tested and I can confirm the `pin-order` branch works well for me.  I like the drag and drop interface for ordering the preferences.  However, having the word "Priority" in the table heading is a little confusing from a usability point of view (I would remove this) as most applications rely on the handles to the left to imply re-ordering is possible.  This means the "Pattern" header would align properly over the matched pattern.

Working configuration for me is:
* `pin-order` branch
* FF 88.0.1 (64-bit)
* Fedora Linux 34

Would be great if you could merge to master and release :-)

**Comment by grahamwhiteuk** [comment]
Is there a planned release date?

**Comment by nicorac** [comment]
Just released 1.3.0 here on GitHub.
Will post it on FF addons, then we have wait for them to approve it 😉

**Comment by grahamwhiteuk** [comment]
Fantastic - thanks very much!
