### ISSUE TITLE
Can't import patterns list on another PC

### ISSUE THREAD

**Issue by fr32k** [coolsoft-ita/autopintab#9]
version 1.2.0
Export works

Click on Import, select the file to be imported, then nothing happens.
Import without function

**Comment by nicorac** [comment]
Import replaces the whole existing list with the one imported from file.
If you're exporting then re-importing the same list, that's why you're not seeing any change.

Try to export the list, then edit something on one or more item, then reimport what you've exported before... You should see that your changes will be reverted ;)

**Comment by fr32k** [comment]
Sorry for my imprecise problem description, I will start again.

I had set up the addon on a PC Firefox and entered things and then exported them, because I saw when I checked the good addon that it has all necessary functions, e.g. export/import.
Then I exported it there.

On another PC Firefox I installed the addon and tried to use the import function and found out that nothing was added to the empty list, the list remained empty.

First check was, are there any data in the *.json?
YES.
Then I added something by hand an entry and tried to import it again, again without success.

Due to time constraints I could not check more deeply, I would be grateful if you could look at it or tell me what I could check more closely.

I hope I explained it a bit better this time.

**Comment by nicorac** [comment]
Ok, so you're exporting list from PC-A and importing that list on PC-B, right?
Well, this is supposed to work...

What you've already tried:
* export list from A and import it on B **(A --> B)**: NOT working

Now what if you:
1. export list from A, edit one of the patterns on A (using AutoPinTab configurator), then reimport the same list on A **(A --> A)**?
2. do the same as point 1) but now on PC B (**B --> B**)?
3. export list from **B --> A**?

After those tests, should be great if you could open Firefox addon debugger (on B) and check for any error message while importing the .json file:

- open `about:debugging#/runtime/this-firefox` URL on Firefox
- click the **Analyze** button next to AutoPinTab addon
- clear all old console messages by clicking the Trash icon
- now import .json file and check if some error appears in the debugger

**Comment by fr32k** [comment]
**Addendum: PC B** is 68.8.0esr (64-bit)

debugger msg

> TypeError: file.text is not a function options.js:125:18
>     Import moz-extension://30002177-1e3f-44fd-981f-aa6da43a3d93/options/options.js:125
>     <anonym> moz-extension://30002177-1e3f-44fd-981f-aa6da43a3d93/options/options.js:35
>     jQuery 2
> 
>

**Comment by nicorac** [comment]
> PC B is 68.8.0esr (64-bit)
This turned the light on 😉.

Thanks to this info (and debugging messages) I was able to reproduce the bug on my side.
Being it an ESR release, I'll try to find a workaround to support v68.
Stay tuned...

**Comment by nicorac** [comment]
Just released version 1.2.1 with a fix for this bug.

You just have to wait for it to be validated and published on Firefox Addons website:
https://addons.mozilla.org/en-US/firefox/addon/autopintab/

Thanks for your report
